# environment variables
environment:
    path_to_sln: src/DnnPackager.sln
    github_accesstoken:
        secure: 0eeao9xU5Ds59SwZLIxr9nPU8Uc5mQOvl/qNJRLynFACF29Ts0ctMFpDDSDjz18U
    github_owner: dazinator
    github_reponame: DnnPackager
skip_tags: true
install:
    - choco install gitversion.portable -pre -y
    - cinst gitlink -version 2.4.1 -y
image: Visual Studio 2017
assembly_info:
    patch: false
configuration: Release
before_build:
    - ps: gitversion /l console /output buildserver
    - cmd: msbuild %path_to_sln% /t:restore /p:PackageVersion=%GitVersion_NuGetVersion%
build:
    project: '%path_to_sln%'
    verbosity: minimal
after_build:
    - cmd: gitlink . -u https://github.com/%APPVEYOR_REPO_NAME% -b %APPVEYOR_REPO_BRANCH% -s %APPVEYOR_REPO_COMMIT% -f %path_to_sln%
    - cmd: msbuild "src/DnnPackager.Tasks/DnnPackager.Tasks.csproj" /t:Pack /p:PackageVersion="%GitVersion_NuGetVersion%" /p:PackageOutputPath="..\..\."
artifacts:
    - path: /DnnPackager*.nupkg
deploy:
    provider: NuGet
    api_key:
        secure: u8JpW5kkti8pMi+ra2QcXTJPhkHCA8pkKSiiZOJbcS/vFVHNvF3W8qw1Fy2If6a7
    skip_symbols: false
    artifact: /.*\.nupkg/
# here we are going to override common configuration
for:
- 
    branches:
        only:
            - master
            - /release.*/
            - /hotfix.*/
    after_build:
        - cmd: "'./tools/GitReleaseNotes.0.6.0/tools/GitReleaseNotes.exe' /OutputFile ReleaseNotes.md /Version %GitVersion_NuGetVersion%"
        - cmd: "'tools/GithubReleaseCreator.1.1.0/tools/GithubReleaseCreator.exe' --username %github_accesstoken% --owner '%github_owner%' --repo '%github_reponame%' --tag '%APPVEYOR_BUILD_VERSION%' --name '%github_reponame% v%GitVersion_NuGetVersion%' --filedesc 'ReleaseNotes.md' --draft --assetfiles 'DnnPackager.%GitVersion_NuGetVersion%.nupkg' --verbose"
- 
    branches:
        only:
            - develop
            - /feature.*/